In [1]:
import torch
torch.tensor([1.2,3.4]).dtype

torch.float32

In [2]:
torch.set_default_tensor_type(torch.DoubleTensor)
# torch.set_default_tensor_type(torch.ByteTensor)
torch.tensor([1.2,3.4]).dtype
# 转化成64位dtype

torch.float64

In [3]:
a=torch.tensor([1.2,3.4])
print("a.dtype:",a.dtype)
print("a.long()方法:",a.long().dtype)
print("a.long()方法:",a.int().dtype)
print("a.long()方法:",a.float().dtype)
# print("a.long()方法:",a.uint8().dtype)
# 这个方法不适用于转化为八位无符号整形以及八位you符号整形

a.dtype: torch.float64
a.long()方法: torch.int64
a.long()方法: torch.int32
a.long()方法: torch.float32


In [4]:
torch.set_default_tensor_type(torch.FloatTensor)
# 修改张量数据类型
torch.tensor([1.2,3.4]).dtype

torch.float32

In [5]:
torch.get_default_dtype()

torch.float32

In [6]:
A=torch.tensor([[1.0,1.0],[2,2]])

A
# 用函数构造张量
A.size()

torch.Size([2, 2])

In [7]:
A.shape
# 获取张量维度

torch.Size([2, 2])

In [8]:
A.size()
# 获取张量形状大小

torch.Size([2, 2])

In [9]:
A.numel()
# 获取张量元素大小

4

In [10]:
B=torch.tensor((1,2,3),dtype=torch.float32,requires_grad=True)
B

tensor([1., 2., 3.], requires_grad=True)

In [11]:
y=B.pow(2).sum()
y.backward()
B.grad
# 计算b**2的梯度，此外计算梯度必须是float型的数据。+

tensor([2., 4., 6.])

In [12]:
C=torch.Tensor([1,2,3,4])
C
# 根据已有数据创建张量

tensor([1., 2., 3., 4.])

In [13]:
D=torch.Tensor(2,3)
D
# 根据形状参数生成的张量，而且第一个二位第一个括号里面的元素个数，第二个为第二个括号里面的元素

tensor([[0.0000e+00, 0.0000e+00, 1.8754e+28],
        [2.0110e+20, 2.6194e+20, 1.0358e-11]])

In [14]:
torch.ones_like(D)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [15]:
torch.zeros_like(D)
# torch.***_like()里面只能放置ones和zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
torch.rand_like(D)
# 生成随机张量

tensor([[0.9552, 0.3820, 0.7963],
        [0.1441, 0.6163, 0.4598]])

In [17]:
E=[[1,2],[3,4]]
E=D.new_tensor(E)
print("D.dtype:",D.dtype)
print("E.dtype:",E.dtype)

D.dtype: torch.float32
E.dtype: torch.float32


In [18]:
D.new_full((3,3),fill_value=1)
D.shape

torch.Size([2, 3])

In [19]:
D.new_zeros((3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [20]:
D.new_empty((3,3))
# 空的和0没有什么区别吗？/

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [21]:
D.new_ones((3,3))
# （3,3）这里应该指的是形状

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [22]:
#  张量与NumPy的数据相互转换
# # 1. numpy数组转换为张量
# torch.as_tensor()和torch.from_numpy()
import numpy as np
F=np.ones((3,3))
Ftensor=torch.as_tensor(F)
Ftensor
# 会输出张量以及张量类型

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [23]:
Ftensor=torch.from_numpy(F)
Ftensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [24]:
Ftensor.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
torch.manual_seed(123)
# 指定平均值以及标准差生成随机数
A=torch.normal(mean=0.0,std=torch.arange(1,5.0))
print(A)
A=torch.normal(mean=0.0,std=torch.arange(1.0))
print(A)
# mean为随机数平均值，std为随机数标准差，
# 此外，mean和std只有一个的时候只会生成一个随机数
# 如果有多个参数会生成多个随机数


tensor([-0.1115,  0.2407, -1.1089, -0.9617])
tensor([0.])


In [26]:
torch.manual_seed(123)
A=torch.normal(mean=torch.arange(1,5.0),std=torch.arange(1,5.0))
print(A)
# 生成标准差为1234张量的函数

tensor([0.8885, 2.2407, 1.8911, 3.0383])


In [27]:
# 在取件[0，1]生成服从均匀分布的张量
torch.manual_seed(123)
B=torch.rand(3,4)
print(B)

tensor([[0.2961, 0.5166, 0.2517, 0.6886],
        [0.0740, 0.8665, 0.1366, 0.1025],
        [0.1841, 0.7264, 0.3153, 0.6871]])


In [28]:
torch.manual_seed(123)
C=torch.ones(2,3)
D=torch.rand_like(C)
print(D)

tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665]])


In [29]:
torch.randn((3,3))

tensor([[ 0.9447,  0.6217, -1.3501],
        [-0.1881, -2.3891, -0.4759],
        [ 1.7603,  0.6547,  0.5490]])

In [30]:
print(torch.randn_like(C))

tensor([[ 0.3671,  0.1219,  0.6466],
        [-1.4168,  0.8429, -0.6307]])


In [31]:
torch.manual_seed(123)
torch.randperm(10)

tensor([2, 0, 8, 1, 3, 7, 4, 9, 5, 6])

In [32]:
torch.linspace(start=1,end=10,steps=5)
# 等距生成张量

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

In [33]:
10**(torch.linspace(start=1,end=10,steps=5))

tensor([1.0000e+01, 1.7783e+03, 3.1623e+05, 5.6234e+07, 1.0000e+10])

In [34]:
torch.logspace(start=0.1,end=1.0,steps=5)
# 以对数为间隔，生成张量，上面的起始值为对数的x

tensor([ 1.2589,  2.1135,  3.5481,  5.9566, 10.0000])

In [35]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])