In [1]:
import torch
import numpy
# 改变张量的形状

A=torch.arange(12.0)
A=A.reshape(3,4)
print(torch.arange(12.0).reshape(3,4))
print(A)
A.resize_(2,6)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])

In [2]:
torch.reshape(input=A,shape=(2,6))
print(torch.reshape(input=A,shape=(2,6)))
print(torch.reshape(input=A,shape=(2,-1)))

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])


In [3]:
# 改变张量的形状
A=torch.arange(12.0).reshape(3,4)
print(A)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [4]:
A.resize_(2,6)
print(A)
B=torch.arange(10.0,19.0).reshape(3,3)
A.resize_as_(B)
print(A)
B

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])
tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])


tensor([[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])

In [5]:
A=torch.arange(12.0).reshape(2,6)
print(A.shape)
B=torch.unsqueeze(A,dim=-3)
print(B.shape)
# 这里的意思是用unsqueeze函数实现插入尺寸为一的新张量
B.shape
B.size()
print(B)
B.numel()
C=B.unsqueeze(dim=3)
# 移除尺所有维度为1的张量
print("C.shape:",C.shape)
D=torch.squeeze(C)
print("D.shape:",D.shape)
E=torch.unsqueeze(C,dim=0)
print("E.shape:",E.shape)

torch.Size([2, 6])
torch.Size([1, 2, 6])
tensor([[[ 0.,  1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10., 11.]]])
C.shape: torch.Size([1, 2, 6, 1])
D.shape: torch.Size([2, 6])
E.shape: torch.Size([1, 1, 2, 6, 1])


In [6]:
A=torch.arange(3)
# 创建一个一维相量
B=A.expand(3,-1)# 3或者-1
#  -1 不改变原来的尺寸（非单例尺寸）
# 这里里面的是数字可以任意改变，与下面对应，但是末尾的那个不行，只能是跟前面对应上
B
B.shape
# expand()方法用于拓展维度

torch.Size([3, 3])

In [7]:
C=torch.arange(6).reshape(2,3)
B=A.expand_as(C)
B

tensor([[0, 1, 2],
        [0, 1, 2]])

In [8]:
C=torch.arange(6).reshape(2,3)
B=A.expand_as(C)
print(B.shape)
D=B.repeat(1,2,2,2)
# tensor.repeat(size)这个的意思是把张量看成一个整体，然后根据指定的形状进行重复填充,
# The number of times to repeat this tensor along each dimension
print(D)
print(D.shape)


torch.Size([2, 3])
tensor([[[[0, 1, 2, 0, 1, 2],
          [0, 1, 2, 0, 1, 2],
          [0, 1, 2, 0, 1, 2],
          [0, 1, 2, 0, 1, 2]],

         [[0, 1, 2, 0, 1, 2],
          [0, 1, 2, 0, 1, 2],
          [0, 1, 2, 0, 1, 2],
          [0, 1, 2, 0, 1, 2]]]])
torch.Size([1, 2, 4, 6])


In [9]:
# 获取张量之中的元素
A=torch.arange(12).reshape(1,3,4)
print(A.shape)
print()
print(A)
print()
print(A[0])
print()
# 获取第0维度之下的矩阵元素,第n维度为第n+1的层
print(A[0,0:2,:-1])
print()
# 获取第0维度下的前两行元素
print(A[0,0:2,:])
print()
# 获取第零维度下的矩阵，最后一行的-4到-1列
print(A[0,-1,-4:-1])


torch.Size([1, 3, 4])

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

tensor([[0, 1, 2],
        [4, 5, 6]])

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])

tensor([ 8,  9, 10])


In [10]:
# 在pytorch里面的话可以将索引设置为读研的布尔值，提取真值的内容
print(A)
B=-A
torch.where(A>5,A,B)
print('\n',torch.where(A>5,A,B))
# 当A>5的时候为TRUE返回x对应位置值，为FALSE的时候为y的值
print('\n',A[A>5])

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]])

 tensor([[[ 0, -1, -2, -3],
         [-4, -5,  6,  7],
         [ 8,  9, 10, 11]]])

 tensor([ 6,  7,  8,  9, 10, 11])


In [11]:
print(A)
torch.tril(A,diagonal=0)
print('\n',torch.tril(A,diagonal=0))
# 获取张量下三角的内容，将上三角的元素全部放置为0。

torch.tril(A,diagonal=1)
print('\n',torch.tril(A,diagonal=1))
# diagonal参数控制要考虑的对角线,对角线没有放置为0

torch.triu(A,diagonal=0)
print('\n',torch.tril(A,diagonal=0))
# 获取矩阵张量上三角的部分，对角线放置为0

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]])

 tensor([[[ 0,  0,  0,  0],
         [ 4,  5,  0,  0],
         [ 8,  9, 10,  0]]])

 tensor([[[ 0,  1,  0,  0],
         [ 4,  5,  6,  0],
         [ 8,  9, 10, 11]]])

 tensor([[[ 0,  0,  0,  0],
         [ 4,  5,  0,  0],
         [ 8,  9, 10,  0]]])


In [12]:
C=A.reshape(3,4)
print(C,'\n')
# 函数里面必须是二维张量
print(torch.diag(C,diagonal=0),'\n')
print(torch.diag(C,diagonal=1),'\n')


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]) 

tensor([ 0,  5, 10]) 

tensor([ 1,  6, 11]) 



In [13]:
torch.diag(torch.tensor([1,2,3]))
# 提供对角线元素生成矩阵向量

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

In [14]:
# 拼接与拆分
A=torch.arange(6).reshape(2,3)
print(A,'\n')
B=torch.linspace(0,10,6).reshape(2,3)
print(B,'\n')
# 在0维连接张量,这里的意思是在各自的维度里面进行连接的意思，即为A,B里面的维度进行连接
C=torch.cat((A,B),dim=0)
print(C,'\n')
# 在1维连接张量
D=torch.cat((A,B),dim=1)
print(D,'\n')
E=torch.cat((A[:,1:2],A,B),dim=1)
print(E,'\n')

tensor([[0, 1, 2],
        [3, 4, 5]]) 

tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]]) 

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 0.,  2.,  4.],
        [ 6.,  8., 10.]]) 

tensor([[ 0.,  1.,  2.,  0.,  2.,  4.],
        [ 3.,  4.,  5.,  6.,  8., 10.]]) 

tensor([[ 1.,  0.,  1.,  2.,  0.,  2.,  4.],
        [ 4.,  3.,  4.,  5.,  6.,  8., 10.]]) 



In [15]:
B=torch.linspace(0,10,6).reshape(2,3)
B

tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])

In [19]:
print(A,'\n')
print(B,'\n')
F=torch.stack((A,B),dim=0)
# torch.stack将多个张量按照指定维度进行拼接,意思是新建一个维度进行相加
# 沿新维度连接张量
C=torch.cat((A,B),dim=0)
print(C,'\n')
print(F,'\n')
print(F.shape)

tensor([[0, 1, 2],
        [3, 4, 5]]) 

tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]]) 

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 0.,  2.,  4.],
        [ 6.,  8., 10.]]) 

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]]) 

torch.Size([2, 2, 3])


In [29]:
# print(E,'\n')
F1,F2=torch.chunk(E,2,dim=0)
# print(F1,'\n')
# print(F2,'\n')
# print(D,'\n')
D1,D2=torch.chunk(D,2,dim=1)
# print(D1,'\n')
# print(D2,'\n')
E1,E2,E3=torch.chunk(E,3,dim=1)
print(E1)
print(E2)
print(E3)


tensor([[1., 0., 1.],
        [4., 3., 4.]])
tensor([[2., 0., 2.],
        [5., 6., 8.]])
tensor([[ 4.],
        [10.]])


In [31]:
D1,D2,D3=torch.split(D,[1,2,3],dim=1)
print(D1)
print(D2)
print(D3)

tensor([[0.],
        [3.]])
tensor([[1., 2.],
        [4., 5.]])
tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])
