In [1]:
import torch
A=torch.tensor([10.0])
B=torch.tensor([10.1])
# tocrh.allclose为比较接近与否的函数，标准不同所以结果不同
print(torch.allclose(A,B,rtol=1e-05,atol=1e-08,equal_nan=False))
print(torch.allclose(A,B,rtol=0.1,atol=0.01,equal_nan=False))

False
True


In [2]:
# equal_nam=True,缺失值可以判断为接近
A=torch.tensor(float("nan"))
# A被赋值为缺失值
print(A)
print(torch.allclose(A,A,equal_nan=False))
print(torch.allclose(A,A,equal_nan=True))

tensor(nan)
False
True


In [3]:

A=torch.tensor([1,2,3,4,5,6])
B=torch.arange(1,7)
# 计算元素是否相同
C=torch.unsqueeze(B,dim=0)
print(torch.eq(A,B))
print(torch.eq(A,C))
# 判断两个张量是否有相同的形状和元素
print(torch.equal(A,B))
print(torch.equal(A,C))

tensor([True, True, True, True, True, True])
tensor([[True, True, True, True, True, True]])
True
False


In [4]:
# torch.ge逐个元素比较是否大于等于>=
# torch.gt是主元素比较大于>

# 逐个元素比较大于等于
print(torch.ge(A,B))
print(torch.ge(A,C))

# 逐个元素比较大于
print(torch.gt(A,B))
print(torch.gt(A,C))

# 逐个元素比较是否小于等于<=
print(torch.le(A,B))

# 逐个元素比较是否小于<
print(torch.lt(A,C))




tensor([True, True, True, True, True, True])
tensor([[True, True, True, True, True, True]])
tensor([False, False, False, False, False, False])
tensor([[False, False, False, False, False, False]])
tensor([True, True, True, True, True, True])
tensor([[False, False, False, False, False, False]])


In [5]:
# torch.ne()函数就是逐个元素比较不等于
print(A,'\n')
print(B,'\n')
print(C,'\n')
print(torch.ne(A,B),'\n')
print(torch.ne(A,C))

tensor([1, 2, 3, 4, 5, 6]) 

tensor([1, 2, 3, 4, 5, 6]) 

tensor([[1, 2, 3, 4, 5, 6]]) 

tensor([False, False, False, False, False, False]) 

tensor([[False, False, False, False, False, False]])


In [6]:
# torch.isnan()函数就是逐个元素比较是否有缺失值
torch.isnan(torch.tensor([0,1,float("nan"),2]))

tensor([False, False,  True, False])

In [7]:
# 矩阵逐个元素相乘
A=torch.arange(6.0).reshape(2,3)
B=torch. linspace(10,20,steps=6).reshape(2,3)
print("A:",A,'\n')
print("B:",B)
# 逐个元素相乘
print(A*B,'\n')
# 逐个元素相除
print(A/B,'\n')
# 逐个元素相加
print(A+B,'\n')
# 逐个元素相减
print(A-B,'\n')
# 逐个元素相除
print(B/A,'\n')


A: tensor([[0., 1., 2.],
        [3., 4., 5.]]) 

B: tensor([[10., 12., 14.],
        [16., 18., 20.]])
tensor([[  0.,  12.,  28.],
        [ 48.,  72., 100.]]) 

tensor([[0.0000, 0.0833, 0.1429],
        [0.1875, 0.2222, 0.2500]]) 

tensor([[10., 13., 16.],
        [19., 22., 25.]]) 

tensor([[-10., -11., -12.],
        [-13., -14., -15.]]) 

tensor([[    inf, 12.0000,  7.0000],
        [ 5.3333,  4.5000,  4.0000]]) 



In [8]:
print("A:",A,'\n')
print("B:",B)
# 张量的幂
print(torch.pow(A,3))
print(A**3)
# 计算张量的指数
print(torch.exp(A))
# 计算张量的对数
print(torch.log(A))
# 计算张量的平方根
print(torch.sqrt(A))
print(A**0.5)
# 计算张量的平方根倒数
print(torch.rsqrt(A))
print(1/(A**0.5))

A: tensor([[0., 1., 2.],
        [3., 4., 5.]]) 

B: tensor([[10., 12., 14.],
        [16., 18., 20.]])
tensor([[  0.,   1.,   8.],
        [ 27.,  64., 125.]])
tensor([[  0.,   1.,   8.],
        [ 27.,  64., 125.]])
tensor([[  1.0000,   2.7183,   7.3891],
        [ 20.0855,  54.5981, 148.4132]])
tensor([[  -inf, 0.0000, 0.6931],
        [1.0986, 1.3863, 1.6094]])
tensor([[0.0000, 1.0000, 1.4142],
        [1.7321, 2.0000, 2.2361]])
tensor([[0.0000, 1.0000, 1.4142],
        [1.7321, 2.0000, 2.2361]])
tensor([[   inf, 1.0000, 0.7071],
        [0.5774, 0.5000, 0.4472]])
tensor([[   inf, 1.0000, 0.7071],
        [0.5774, 0.5000, 0.4472]])


In [9]:
# 根据最大值裁剪torch.clamp_max(),根据最小值裁剪torch.clamp_min()和范围裁剪torch.clamp()

print("A:",A,"\n")
# 根据最大裁剪
print(torch.clamp_max(A,4))
# 根据最小值裁剪
print(torch.clamp_min(A,3))
#根据范围裁剪
print(torch.clamp(A,2.5,4))





A: tensor([[0., 1., 2.],
        [3., 4., 5.]]) 

tensor([[0., 1., 2.],
        [3., 4., 4.]])
tensor([[3., 3., 3.],
        [3., 4., 5.]])
tensor([[2.5000, 2.5000, 2.5000],
        [3.0000, 4.0000, 4.0000]])


In [10]:
# 对于张量矩阵的一些运算
A=torch.arange(6.0).reshape(2,3)
print("A:",A,"\n")
# 矩阵的转置
C=torch.t(A)
print(C)
# 矩阵运算，矩阵相乘，A的行数要等于C的列数
print(A.matmul(C))
A=torch.arange(12.0).reshape(2,2,3)
B=torch.arange(12.0).reshape(2,3,2)
AB=torch.matmul(A,B)
print(AB)
# 矩阵相乘只计算最后两个维度的乘法
print(AB[0].eq(torch.matmul(A[0],B[0])))
print(AB[1].eq(torch.matmul(A[1],B[1])))



A: tensor([[0., 1., 2.],
        [3., 4., 5.]]) 

tensor([[0., 3.],
        [1., 4.],
        [2., 5.]])
tensor([[ 5., 14.],
        [14., 50.]])
tensor([[[ 10.,  13.],
         [ 28.,  40.]],

        [[172., 193.],
         [244., 274.]]])
tensor([[True, True],
        [True, True]])
tensor([[True, True],
        [True, True]])


In [11]:
C=torch.rand(3,3)
# 计算矩阵的逆矩阵，而且用inversehanhsu1
D=torch.inverse(C)
print("C:",C,"\n")
print(torch.mm(C,D))
# 计算对角线元素的和，而且对角线元素的和成为矩阵的迹
print(torch.trace(torch.arange(9.0).reshape(3,3)))

C: tensor([[0.9099, 0.1136, 0.9527],
        [0.9357, 0.1133, 0.1987],
        [0.3972, 0.3088, 0.3452]]) 

tensor([[ 1.0000e+00,  0.0000e+00,  4.6566e-08],
        [ 0.0000e+00,  1.0000e+00, -1.6298e-09],
        [ 2.9802e-08,  2.9802e-08,  1.0000e+00]])
tensor(12.)


In [12]:
A=torch.tensor([12.,34,25,11,67,32,29,30,99,55,23,44])
# 最大值以及最大值的位置
print("最大值:",A.max())
print("最大值位置：",A.argmax())
# 最小值以及最小值的位置
print("最小值:",A.min())
print("最小值位置：",A.argmin())
B=A.reshape(3,4)
# 二维张量的最大值以及最小值
print("2-D张量B:\n",B)
# 最大值以及每行最大值的位置
print("最大值：\n",B.max(dim=1))
print("最大值的位置：",B.argmax(dim=1))
# 最小值以及位置（每列）
print("最小值:\n",B.min(dim=0))
print("最小值的位置：",B.argmin(dim=0))


最大值: tensor(99.)
最大值位置： tensor(8)
最小值: tensor(11.)
最小值位置： tensor(3)
2-D张量B:
 tensor([[12., 34., 25., 11.],
        [67., 32., 29., 30.],
        [99., 55., 23., 44.]])
最大值：
 torch.return_types.max(
values=tensor([34., 67., 99.]),
indices=tensor([1, 0, 0]))
最大值的位置： tensor([1, 0, 0])
最小值:
 torch.return_types.min(
values=tensor([12., 32., 23., 11.]),
indices=tensor([0, 1, 2, 0]))
最小值的位置： tensor([0, 1, 2, 0])


In [13]:
# 对于以为张量进行排序，或者对于高位张量的一个指定维度排序，
# 按照升序排列
print("A:",A,"\n")
print(torch.sort(A))
# 按照降序排列
print(torch.sort(A,descending=True))
# 对2D张量进行排序
print("B:",B,"\n")
Bsort,Bsort_id=torch.sort(B)
print("B sort:\n",Bsort)
print("B sort index:\n",Bsort_id)
print("B argsort:\n",torch.argsort(B))



A: tensor([12., 34., 25., 11., 67., 32., 29., 30., 99., 55., 23., 44.]) 

torch.return_types.sort(
values=tensor([11., 12., 23., 25., 29., 30., 32., 34., 44., 55., 67., 99.]),
indices=tensor([ 3,  0, 10,  2,  6,  7,  5,  1, 11,  9,  4,  8]))
torch.return_types.sort(
values=tensor([99., 67., 55., 44., 34., 32., 30., 29., 25., 23., 12., 11.]),
indices=tensor([ 8,  4,  9, 11,  1,  5,  7,  6,  2, 10,  0,  3]))
B: tensor([[12., 34., 25., 11.],
        [67., 32., 29., 30.],
        [99., 55., 23., 44.]]) 

B sort:
 tensor([[11., 12., 25., 34.],
        [29., 30., 32., 67.],
        [23., 44., 55., 99.]])
B sort index:
 tensor([[3, 0, 2, 1],
        [2, 3, 1, 0],
        [2, 3, 1, 0]])
B argsort:
 tensor([[3, 0, 2, 1],
        [2, 3, 1, 0],
        [2, 3, 1, 0]])


In [14]:
# 获取张量前几个大的数值
torch.topk(A,4)
# 获取2-D张量每列前几个大的数值
print("\nB:\n",B)
Btop2,Btop2_id=torch.topk(B,2,dim=0)
print("B 每列top2:\n",Btop2)
print("B top2 的位置\n",Btop2_id)
# 获取张量第k小的数值以及位置
print(torch.kthvalue(A,3))
# 获取2--D张量第k小的数值以及位置
print(torch.kthvalue(B,3,dim=1))
# 获取张量第k小的数值以及位置
Bkth,Bkth_id=torch.kthvalue(B,3,dim=1,keepdim=True)
print("Bktn:",Bkth)





B:
 tensor([[12., 34., 25., 11.],
        [67., 32., 29., 30.],
        [99., 55., 23., 44.]])
B 每列top2:
 tensor([[99., 55., 29., 44.],
        [67., 34., 25., 30.]])
B top2 的位置
 tensor([[2, 2, 1, 2],
        [1, 0, 0, 1]])
torch.return_types.kthvalue(
values=tensor(23.),
indices=tensor(10))
torch.return_types.kthvalue(
values=tensor([25., 32., 55.]),
indices=tensor([2, 1, 1]))
Bktn: tensor([[25.],
        [32.],
        [55.]])


In [21]:
# 平均值，计算每行的均值
print("B:",B,"\n")
print(torch.mean(B,dim=1,keepdim=True),torch.mean(B,dim=1,keepdim=True).size())
print(torch.mean(B,dim=1,keepdim=False),torch.mean(B,dim=1,keepdim=False).size())
# 平均值，计算每列的均值
print(torch.mean(B,dim=0,keepdim=True))
# 计算每行的和
print(torch.sum(B,dim=1,keepdim=True))
# 计算每列的和
print(torch.sum(B,dim=0,keepdim=True))
# 按照行计算累加和
print(torch.cumsum(B,dim=1))
# 按照列计算累加和
print(torch.cumsum(B,dim=0))
# 计算每行的中位数
print(torch.median(B,dim=1,keepdim=True))
# 计算每列的中位数
print(torch.median(B,dim=0,keepdim=True))

B: tensor([[12., 34., 25., 11.],
        [67., 32., 29., 30.],
        [99., 55., 23., 44.]]) 

tensor([[20.5000],
        [39.5000],
        [55.2500]]) torch.Size([3, 1])
tensor([20.5000, 39.5000, 55.2500]) torch.Size([3])
tensor([[59.3333, 40.3333, 25.6667, 28.3333]])
tensor([[ 82.],
        [158.],
        [221.]])
tensor([[178., 121.,  77.,  85.]])
tensor([[ 12.,  46.,  71.,  82.],
        [ 67.,  99., 128., 158.],
        [ 99., 154., 177., 221.]])
tensor([[ 12.,  34.,  25.,  11.],
        [ 79.,  66.,  54.,  41.],
        [178., 121.,  77.,  85.]])
torch.return_types.median(
values=tensor([[12.],
        [30.],
        [44.]]),
indices=tensor([[0],
        [3],
        [3]]))
torch.return_types.median(
values=tensor([[67., 34., 25., 30.]]),
indices=tensor([[1, 0, 0, 1]]))


In [23]:
# 按照计行计算乘积
print(torch.prod(B,dim=1,keepdim=True))
# 按照列计算乘积
print(torch.prod(B,dim=0,keepdim=True))
# 按照行计算累乘积
print(torch.cumprod(B,dim=1))
# 按照列计算累乘积
print(torch.cumprod(B,dim=0))
# 标准差
print(torch.std(A))

tensor([[ 112200.],
        [1865280.],
        [5510340.]])
tensor([[79596., 59840., 16675., 14520.]])
tensor([[1.2000e+01, 4.0800e+02, 1.0200e+04, 1.1220e+05],
        [6.7000e+01, 2.1440e+03, 6.2176e+04, 1.8653e+06],
        [9.9000e+01, 5.4450e+03, 1.2524e+05, 5.5103e+06]])
tensor([[1.2000e+01, 3.4000e+01, 2.5000e+01, 1.1000e+01],
        [8.0400e+02, 1.0880e+03, 7.2500e+02, 3.3000e+02],
        [7.9596e+04, 5.9840e+04, 1.6675e+04, 1.4520e+04]])
tensor(25.0108)


In [ ]:
import torch
# 实现任意标量值函数自动求导的类和函数
# 针对一个张量只需要设置参数requires_grad,即可输出传播过程中的梯度信息
x=torch.tensor([[1.0,2.0],[3.0,4.0]],requires_grad=True)
# 默认require_grad=False
y=torch.sum(x**2+2*x+1)
# y 的导数是2x+2
print("X.requires_grad:",x.requires_grad)
print("y.requires_grad:",y.requires_grad)
print("x:",x)
print("y:",y)
# 计算y在x的梯度
print(y.backward())
print(x.grad)